# Generated by Django 5.1.6 on 2025-03-14 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pawfect', '0005_alter_comment_options_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='time',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='images',
        ),
        migrations.CreateModel(
            name='CommentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='comment_images/')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Pawfect.comment')),
            ],
        ),
    ]
